23-08-17 02:04:00 Loading /usr/src/evennia/evennia/server/server.py...
23-08-17 02:04:00 Loaded.
23-08-17 02:04:00 twistd 19.2.1 (/usr/local/bin/python 3.7.3) starting up.
23-08-17 02:04:00 reactor class: twisted.internet.epollreactor.EPollReactor.
23-08-17 02:04:00 Webserver starting on 4005
23-08-17 02:04:00 [..] Initial setup: Creating objects (Account #1 and Limbo room) ...
23-08-17 02:04:01 Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/usr/local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/usr/local/lib/python3.7/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/usr/src/evennia/evennia/server/portal/amp.py", line 328, in makeConnection
	    amp.BinaryBoxProtocol.makeConnection(self, transport)
	  File "/usr/local/lib/python3.7/site-packages/twisted/protocols/amp.py", line 2396, in makeConnection
	    self.connectionMade()
	  File "/usr/src/evennia/evennia/server/amp_client.py", line 113, in connectionMade
	    self.factory.server.run_initial_setup()
	  File "/usr/src/evennia/evennia/server/server.py", line 287, in run_initial_setup
	    initial_setup.handle_setup(0)
	  File "/usr/src/evennia/evennia/server/initial_setup.py", line 209, in handle_setup
	    setup_func()
	  File "/usr/src/evennia/evennia/server/initial_setup.py", line 88, in create_objects
	    nohome=True)
	  File "/usr/src/evennia/evennia/utils/create.py", line 137, in create_object
	    new_object.save()
	  File "/usr/src/evennia/evennia/utils/idmapper/models.py", line 396, in save
	    super().save(*args, **kwargs)
	  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 718, in save
	    force_update=force_update, update_fields=update_fields)
	  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 758, in save_base
	    update_fields=update_fields, raw=raw, using=using,
	  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
	    for receiver in self._live_receivers(sender)
	  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
	    for receiver in self._live_receivers(sender)
	  File "/usr/src/evennia/evennia/typeclasses/models.py", line 71, in call_at_first_save
	    instance.at_first_save()
	  File "/usr/src/evennia/evennia/objects/objects.py", line 1066, in at_first_save
	    self.at_object_creation()
	  File "/usr/src/game/pq4/typeclasses/characters.py", line 69, in at_object_creation
	    self.pop_inven()
	  File "/usr/src/game/pq4/typeclasses/characters.py", line 40, in pop_inven
	    spawn(self.mj_proto)
	  File "/usr/src/evennia/evennia/prototypes/spawner.py", line 736, in spawn
	    create_kwargs["db_home"] = init_spawn_value(val, value_to_obj)
	  File "/usr/src/evennia/evennia/prototypes/prototypes.py", line 747, in init_spawn_value
	    value = validator(value)
	  File "/usr/src/evennia/evennia/prototypes/prototypes.py", line 772, in value_to_obj
	    return dbid_to_obj(value, ObjectDB)
	  File "/usr/src/evennia/evennia/utils/utils.py", line 738, in dbref_to_obj
	    return objclass.objects.get(id=dbid)
	  File "/usr/src/evennia/evennia/utils/idmapper/manager.py", line 32, in get
	    inst = super().get(*args, **kwargs)
	  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
	    return getattr(self.get_queryset(), name)(*args, **kwargs)
	  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
	    self.model._meta.object_name
	evennia.objects.models.DoesNotExist: ObjectDB matching query does not exist.
	
23-08-17 02:04:01 [..] Server disconnected from the portal.
23-08-17 02:04:02 [..] Initial setup: Creating objects (Account #1 and Limbo room) ...
23-08-17 02:04:03 [..] Initial setup: Creating default channels ...
23-08-17 02:04:03 [..] Initial setup: Running at_initial_setup() hook.
23-08-17 02:04:03 [..] Initial setup: Gathering static resources using 'collectstatic'
23-08-17 02:04:03 
23-08-17 02:04:03 0 static files copied to '/usr/src/game/pq4/web/static', 150 unmodified.
23-08-17 02:04:03 [..] Initial setup complete. Restarting Server once.
23-08-17 02:04:03 Evennia Server successfully started.
23-08-17 02:04:04 [..] Server disconnected from the portal.
23-08-17 02:04:04 Main loop terminated.
23-08-17 02:04:04 Server Shut Down.
23-08-17 02:04:04 Loading /usr/src/evennia/evennia/server/server.py...
23-08-17 02:04:05 Loaded.
23-08-17 02:04:05 twistd 19.2.1 (/usr/local/bin/python 3.7.3) starting up.
23-08-17 02:04:05 reactor class: twisted.internet.epollreactor.EPollReactor.
23-08-17 02:04:05 Webserver starting on 4005
23-08-17 02:04:05 Evennia Server successfully restarted in 'reset' mode.
